Add dependency on future to setup.py
A change was introduced in a5bb019 to use the future package for
Python 2/3 compatibility, but the package was not added as a
dependency to setup.py. A system without future installed and
installs ibm_db_sa will fail with:

Traceback (most recent call last):
File "alchemy_test.py", line 3, in <module>
import ibm_db_sa.ibm_db_sa
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/init.py", line 22, in <module>
from . import ibm_db, pyodbc, base, zxjdbc
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/ibm_db.py", line 20, in <module>
from .base import DB2ExecutionContext, DB2Dialect
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/base.py", line 30, in <module>
from . import reflection as ibm_reflection
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/reflection.py", line 26, in <module>
from future.utils import iteritems
ModuleNotFoundError: No module named 'future'

Also fix project URLs